name: demo-action
on: [ push ]
jobs:
    deploy:
        name: Demo Terraform
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        defaults:
            run:
                working-directory: terraform


        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Update EC2 instance
          run: |
            terraform init && \
                terraform destroy -target=aws_instance.ec2_runner \
                -var-file=cbi_poc.tfvars -var="github_token=${GITHUB_TOKEN}" -auto-approve || true && \
                terraform apply -var-file=cbi_poc.tfvars -var="github_token=${GITHUB_TOKEN}" \
                -auto-approve
