name: demo-action
on: [ push ]
jobs:
    deploy:
        name: Test Your Action
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Create a VPC
          run: |
            terraform init && terraform plan
          with:
            path: terraform
